### ISSUE TITLE
How to use your trained model.

### ISSUE THREAD

**Issue by pangzhan27** [Finspire13/DiffAct#5]
Thanks for sharing your code.
I want to test on your trained model. 
The model size is too small, only ~4 MB.  Is it just a placeholder? 
If yes, could you provide your models for testing?
If no, could you give me some suggestions how to use your provided models. 

Many thanks!

**Comment by Finspire13** [comment]
Hi pangzhan27, the released models can be used for testing. You can use the test function in main.py (https://github.com/Finspire13/DiffAct/blob/main/main.py#L280C9-L280C13) and specifying the model_path.

**Comment by pangzhan27** [comment]
Thank you so much.
