### ISSUE TITLE
How those videos been extracted?

### ISSUE THREAD

**Issue by WuZhuoran** [Finspire13/DiffAct#7]
Hi Author,

Thanks for your work. I found that we can download the datasets with pre calculated dataset. Almost all the papers, they will use those pre calclulated data.

Do you know how those features are been extracted? For example, which model that used to extract? And does your model could accept different features from different models?

I heard that there is a widely used repo: https://github.com/v-iashin/video_features
There are many models support for `frame-wise` features such as ViT or CLIP or ResNet.

Do you know which features that your code use and did you use some code or tools to calculate them? Thanks

**Comment by Finspire13** [comment]
Those features were extracted by MSTCN (if I remember correctly), and the following works use the same features for easier comparison. The features were extracted by I3D.

Yes, different features can be used, as long as you make sure they have some similar tensor shape.

**Comment by WuZhuoran** [comment]
> Those features were extracted by MSTCN (if I remember correctly), and the following works use the same features for easier comparison. The features were extracted by I3D.
> 
> Yes, different features can be used, as long as you make sure they have some similar tensor shape.

Thanks for your reply! That is very helpful! I have one follow up question:

Why choose I3D feature? For you or previous MSTCN work? There are some other choices such as S3D/R3D etc. Also there are some frame-wise or Optical flow based features. Why choose I3D? 

Thank you!

**Comment by Finspire13** [comment]
I guess I3D was the most widely used at the time of MSTCN and later papers just follow it. No particular reason.
